// <auto-generated />
using System;
using BusRouteManagementSystem.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BusRouteManagementSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.6.23329.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BusBusStop", b =>
                {
                    b.Property<Guid>("BusesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StopsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BusesId", "StopsId");

                    b.HasIndex("StopsId");

                    b.ToTable("BusBusStop");
                });

            modelBuilder.Entity("BusRouteManagementSystem.Model.Bus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BusName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Bus");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9c1d3c8c-99b6-4df7-bca1-74e78ce8e5ca"),
                            BusName = "Mahanagar yatayat",
                            BusNumber = "MY1"
                        },
                        new
                        {
                            Id = new Guid("b5f8236a-927e-471e-8c75-66cf17f06df7"),
                            BusName = "saja yatayat",
                            BusNumber = "MY2"
                        },
                        new
                        {
                            Id = new Guid("0a97006a-8769-456a-8c85-674a547c1e2a"),
                            BusName = "Mahasagar yatayat",
                            BusNumber = "MY3"
                        },
                        new
                        {
                            Id = new Guid("6fa37e09-6e66-4f05-9d3e-2d8d57b24e18"),
                            BusName = "Gagalfedi yatayat",
                            BusNumber = "MY4"
                        },
                        new
                        {
                            Id = new Guid("59f6e2c2-7355-4c9b-80bb-41db468cf1ab"),
                            BusName = "Micro BUS",
                            BusNumber = "MY6"
                        },
                        new
                        {
                            Id = new Guid("4e1c45c7-9b43-4ef5-a63d-bc6e0f932c5f"),
                            BusName = "Gokerneshwor",
                            BusNumber = "MY7"
                        });
                });

            modelBuilder.Entity("BusRouteManagementSystem.Model.BusBusStop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BusStopId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BusStopNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BusId");

                    b.HasIndex("BusStopId");

                    b.ToTable("BusBusStops");

                    b.HasData(
                        new
                        {
                            Id = new Guid("04f7fc1a-1dcd-4a98-94f3-22a54a9b6c72"),
                            BusId = new Guid("4e1c45c7-9b43-4ef5-a63d-bc6e0f932c5f"),
                            BusStopId = new Guid("e4b9c7d3-1f8a-4672-92e5-6c3dab7f5e9d"),
                            BusStopNo = 1
                        },
                        new
                        {
                            Id = new Guid("b8ed93df-8b5d-4d13-a99f-794f7be43c46"),
                            BusId = new Guid("4e1c45c7-9b43-4ef5-a63d-bc6e0f932c5f"),
                            BusStopId = new Guid("e8a4cf7f-31fc-4b09-a57e-8a1c6e741b85"),
                            BusStopNo = 2
                        },
                        new
                        {
                            Id = new Guid("3e9d01b6-894d-4f26-b17b-8c5d5d5d18e1"),
                            BusId = new Guid("4e1c45c7-9b43-4ef5-a63d-bc6e0f932c5f"),
                            BusStopId = new Guid("d6c9e7b3-268f-44a2-bf24-4e82eb6efb36"),
                            BusStopNo = 3
                        },
                        new
                        {
                            Id = new Guid("7f52c417-63e1-4a7a-9fe6-9b2ca63c3e0e"),
                            BusId = new Guid("4e1c45c7-9b43-4ef5-a63d-bc6e0f932c5f"),
                            BusStopId = new Guid("c4e4a12d-2b5a-4a97-8493-327ad0869f6a"),
                            BusStopNo = 4
                        },
                        new
                        {
                            Id = new Guid("2c7c191e-6bc7-46d5-a71d-9b73fbbef4b0"),
                            BusId = new Guid("4e1c45c7-9b43-4ef5-a63d-bc6e0f932c5f"),
                            BusStopId = new Guid("7a3f1d02-5c79-4803-9a2f-1c8559d3077d"),
                            BusStopNo = 5
                        },
                        new
                        {
                            Id = new Guid("1785c8eb-6c10-4c0f-88a3-2a5f3ef1ce2a"),
                            BusId = new Guid("4e1c45c7-9b43-4ef5-a63d-bc6e0f932c5f"),
                            BusStopId = new Guid("6a65a3eb-901e-418f-bb3f-9ac0c68a9c64"),
                            BusStopNo = 6
                        },
                        new
                        {
                            Id = new Guid("986dbec4-3e16-4a8d-9b3b-06d9ac10543b"),
                            BusId = new Guid("59f6e2c2-7355-4c9b-80bb-41db468cf1ab"),
                            BusStopId = new Guid("2c171bb1-63a7-42d9-91e2-83de835c85a1"),
                            BusStopNo = 1
                        },
                        new
                        {
                            Id = new Guid("6d9f5e0d-4cf2-4a6d-8f1f-835fbf30753d"),
                            BusId = new Guid("59f6e2c2-7355-4c9b-80bb-41db468cf1ab"),
                            BusStopId = new Guid("e8a4cf7f-31fc-4b09-a57e-8a1c6e741b85"),
                            BusStopNo = 2
                        },
                        new
                        {
                            Id = new Guid("bcf3e70c-3f4b-48e6-b1b9-c6e01b07f0f4"),
                            BusId = new Guid("59f6e2c2-7355-4c9b-80bb-41db468cf1ab"),
                            BusStopId = new Guid("d6c9e7b3-268f-44a2-bf24-4e82eb6efb36"),
                            BusStopNo = 3
                        },
                        new
                        {
                            Id = new Guid("1a72f6a8-c7b9-45e1-8f59-3b45d81c71ac"),
                            BusId = new Guid("59f6e2c2-7355-4c9b-80bb-41db468cf1ab"),
                            BusStopId = new Guid("c4e4a12d-2b5a-4a97-8493-327ad0869f6a"),
                            BusStopNo = 4
                        },
                        new
                        {
                            Id = new Guid("3b6c7d2b-89f6-4f70-ae6b-147dab2e9243"),
                            BusId = new Guid("59f6e2c2-7355-4c9b-80bb-41db468cf1ab"),
                            BusStopId = new Guid("7a3f1d02-5c79-4803-9a2f-1c8559d3077d"),
                            BusStopNo = 5
                        },
                        new
                        {
                            Id = new Guid("a5f8e7d1-4b9c-4e2d-93c7-8fd291c874a0"),
                            BusId = new Guid("59f6e2c2-7355-4c9b-80bb-41db468cf1ab"),
                            BusStopId = new Guid("42d08f38-8756-4c09-b5df-6a65b5f8d0fe"),
                            BusStopNo = 6
                        },
                        new
                        {
                            Id = new Guid("b3e92c52-581c-4f69-9c02-d6b96e12f64d"),
                            BusId = new Guid("59f6e2c2-7355-4c9b-80bb-41db468cf1ab"),
                            BusStopId = new Guid("9f7b8e26-3ac9-467d-9b3e-688a63b8d1e5"),
                            BusStopNo = 1
                        },
                        new
                        {
                            Id = new Guid("2e871889-45a4-4ab5-aa65-7f6cc9e95115"),
                            BusId = new Guid("59f6e2c2-7355-4c9b-80bb-41db468cf1ab"),
                            BusStopId = new Guid("e8a4cf7f-31fc-4b09-a57e-8a1c6e741b85"),
                            BusStopNo = 2
                        },
                        new
                        {
                            Id = new Guid("ebae82c2-8db4-4630-b1d4-7c3e56c3d44d"),
                            BusId = new Guid("59f6e2c2-7355-4c9b-80bb-41db468cf1ab"),
                            BusStopId = new Guid("d6c9e7b3-268f-44a2-bf24-4e82eb6efb36"),
                            BusStopNo = 3
                        },
                        new
                        {
                            Id = new Guid("18cb1a0e-2c4b-4ea7-b93f-43914d106d5e"),
                            BusId = new Guid("59f6e2c2-7355-4c9b-80bb-41db468cf1ab"),
                            BusStopId = new Guid("c4e4a12d-2b5a-4a97-8493-327ad0869f6a"),
                            BusStopNo = 4
                        },
                        new
                        {
                            Id = new Guid("e0ce685a-5867-401e-bb7e-91b59b1bea3a"),
                            BusId = new Guid("59f6e2c2-7355-4c9b-80bb-41db468cf1ab"),
                            BusStopId = new Guid("7a3f1d02-5c79-4803-9a2f-1c8559d3077d"),
                            BusStopNo = 5
                        },
                        new
                        {
                            Id = new Guid("894af329-0137-4f1b-99f1-6f1a58f4e22a"),
                            BusId = new Guid("59f6e2c2-7355-4c9b-80bb-41db468cf1ab"),
                            BusStopId = new Guid("42d08f38-8756-4c09-b5df-6a65b5f8d0fe"),
                            BusStopNo = 6
                        },
                        new
                        {
                            Id = new Guid("d5788ea1-7403-48c9-874d-0d5c3edf1ea2"),
                            BusId = new Guid("0a97006a-8769-456a-8c85-674a547c1e2a"),
                            BusStopId = new Guid("9f7b8e26-3ac9-467d-9b3e-688a63b8d1e5"),
                            BusStopNo = 1
                        },
                        new
                        {
                            Id = new Guid("82378d4c-7a7d-4b18-89d5-c1a0fe738b2e"),
                            BusId = new Guid("0a97006a-8769-456a-8c85-674a547c1e2a"),
                            BusStopId = new Guid("e8a4cf7f-31fc-4b09-a57e-8a1c6e741b85"),
                            BusStopNo = 2
                        },
                        new
                        {
                            Id = new Guid("f3d98ed6-38fe-49e5-9075-0b2c300d5e5a"),
                            BusId = new Guid("0a97006a-8769-456a-8c85-674a547c1e2a"),
                            BusStopId = new Guid("d6c9e7b3-268f-44a2-bf24-4e82eb6efb36"),
                            BusStopNo = 3
                        },
                        new
                        {
                            Id = new Guid("48656d8f-4ee6-45b3-9602-180e913f0a47"),
                            BusId = new Guid("0a97006a-8769-456a-8c85-674a547c1e2a"),
                            BusStopId = new Guid("c4e4a12d-2b5a-4a97-8493-327ad0869f6a"),
                            BusStopNo = 4
                        },
                        new
                        {
                            Id = new Guid("160c50e6-1b24-45a6-9db1-0d0b387c9c07"),
                            BusId = new Guid("0a97006a-8769-456a-8c85-674a547c1e2a"),
                            BusStopId = new Guid("7fe7e1cb-63a2-4c6e-940f-63e7c85728c7"),
                            BusStopNo = 5
                        },
                        new
                        {
                            Id = new Guid("75a17dd9-1a63-4e5d-97b5-26b219d69597"),
                            BusId = new Guid("0a97006a-8769-456a-8c85-674a547c1e2a"),
                            BusStopId = new Guid("b8fbbac3-e95a-47c7-950f-75e73a2ea4c9"),
                            BusStopNo = 6
                        },
                        new
                        {
                            Id = new Guid("5dc48e06-50f7-47b5-9e0d-72d856ec3a63"),
                            BusId = new Guid("6fa37e09-6e66-4f05-9d3e-2d8d57b24e18"),
                            BusStopId = new Guid("5b5f8d4a-0c62-4c06-94e1-aa6f02a7a1df"),
                            BusStopNo = 1
                        },
                        new
                        {
                            Id = new Guid("4fb2deac-87b7-4717-b82c-7db77197f846"),
                            BusId = new Guid("6fa37e09-6e66-4f05-9d3e-2d8d57b24e18"),
                            BusStopId = new Guid("9f7b8e26-3ac9-467d-9b3e-688a63b8d1e5"),
                            BusStopNo = 2
                        },
                        new
                        {
                            Id = new Guid("7d1f8e45-7c3e-4c63-8cfc-d8a73c1a70a5"),
                            BusId = new Guid("6fa37e09-6e66-4f05-9d3e-2d8d57b24e18"),
                            BusStopId = new Guid("e8a4cf7f-31fc-4b09-a57e-8a1c6e741b85"),
                            BusStopNo = 3
                        },
                        new
                        {
                            Id = new Guid("a2e8f174-7fb3-40a5-bf65-47c0a8b36525"),
                            BusId = new Guid("6fa37e09-6e66-4f05-9d3e-2d8d57b24e18"),
                            BusStopId = new Guid("d6c9e7b3-268f-44a2-bf24-4e82eb6efb36"),
                            BusStopNo = 4
                        },
                        new
                        {
                            Id = new Guid("6eaa7ef5-81a7-4151-a1f7-4f2a82b7679b"),
                            BusId = new Guid("6fa37e09-6e66-4f05-9d3e-2d8d57b24e18"),
                            BusStopId = new Guid("c4e4a12d-2b5a-4a97-8493-327ad0869f6a"),
                            BusStopNo = 5
                        },
                        new
                        {
                            Id = new Guid("c75a12e7-6e4c-4be0-8e48-33de929cd6b7"),
                            BusId = new Guid("6fa37e09-6e66-4f05-9d3e-2d8d57b24e18"),
                            BusStopId = new Guid("7a3f1d02-5c79-4803-9a2f-1c8559d3077d"),
                            BusStopNo = 6
                        },
                        new
                        {
                            Id = new Guid("94f9630b-e4c9-42d5-b71b-7d44219ab77c"),
                            BusId = new Guid("6fa37e09-6e66-4f05-9d3e-2d8d57b24e18"),
                            BusStopId = new Guid("42d08f38-8756-4c09-b5df-6a65b5f8d0fe"),
                            BusStopNo = 7
                        },
                        new
                        {
                            Id = new Guid("f3a4e1c9-0c09-4fe4-812d-1b2ff591a195"),
                            BusId = new Guid("6fa37e09-6e66-4f05-9d3e-2d8d57b24e18"),
                            BusStopId = new Guid("b8fbbac3-e95a-47c7-950f-75e73a2ea4c9"),
                            BusStopNo = 8
                        },
                        new
                        {
                            Id = new Guid("e5ea6b7d-4d03-46f1-a3f7-54a58a5047e1"),
                            BusId = new Guid("0a97006a-8769-456a-8c85-674a547c1e2a"),
                            BusStopId = new Guid("d2722cf0-2bfa-4e0e-b5c0-2c482c74b6a2"),
                            BusStopNo = 1
                        },
                        new
                        {
                            Id = new Guid("501d3e3b-4c2d-432f-b81d-94b5d9814322"),
                            BusId = new Guid("0a97006a-8769-456a-8c85-674a547c1e2a"),
                            BusStopId = new Guid("2c171bb1-63a7-42d9-91e2-83de835c85a1"),
                            BusStopNo = 2
                        },
                        new
                        {
                            Id = new Guid("f43b6e6a-665b-47e3-b698-5d396c62cabe"),
                            BusId = new Guid("0a97006a-8769-456a-8c85-674a547c1e2a"),
                            BusStopId = new Guid("e8a4cf7f-31fc-4b09-a57e-8a1c6e741b85"),
                            BusStopNo = 3
                        },
                        new
                        {
                            Id = new Guid("82daafaf-6090-4e66-979b-1a939df19f29"),
                            BusId = new Guid("0a97006a-8769-456a-8c85-674a547c1e2a"),
                            BusStopId = new Guid("c4e4a12d-2b5a-4a97-8493-327ad0869f6a"),
                            BusStopNo = 4
                        },
                        new
                        {
                            Id = new Guid("e302d6ac-7a6f-4e9d-aae7-46d8b2a9948e"),
                            BusId = new Guid("0a97006a-8769-456a-8c85-674a547c1e2a"),
                            BusStopId = new Guid("7a3f1d02-5c79-4803-9a2f-1c8559d3077d"),
                            BusStopNo = 5
                        },
                        new
                        {
                            Id = new Guid("6dbf0e5e-85a9-4e02-bc77-b67d7711c18d"),
                            BusId = new Guid("0a97006a-8769-456a-8c85-674a547c1e2a"),
                            BusStopId = new Guid("42d08f38-8756-4c09-b5df-6a65b5f8d0fe"),
                            BusStopNo = 6
                        },
                        new
                        {
                            Id = new Guid("ec788798-6b1a-45e3-9ef1-3d589f8626d3"),
                            BusId = new Guid("9c1d3c8c-99b6-4df7-bca1-74e78ce8e5ca"),
                            BusStopId = new Guid("cc376167-8b1a-4df7-bfd3-48e3542f73c5"),
                            BusStopNo = 1
                        },
                        new
                        {
                            Id = new Guid("f95f792b-0b47-4eeb-8e9a-652edbd46c9d"),
                            BusId = new Guid("9c1d3c8c-99b6-4df7-bca1-74e78ce8e5ca"),
                            BusStopId = new Guid("5b5f8d4a-0c62-4c06-94e1-aa6f02a7a1df"),
                            BusStopNo = 2
                        },
                        new
                        {
                            Id = new Guid("9af1d2f0-52bb-4d3f-8a47-cbdfcb85b4d9"),
                            BusId = new Guid("9c1d3c8c-99b6-4df7-bca1-74e78ce8e5ca"),
                            BusStopId = new Guid("9f7b8e26-3ac9-467d-9b3e-688a63b8d1e5"),
                            BusStopNo = 3
                        },
                        new
                        {
                            Id = new Guid("8eef0d79-717d-4da1-bbb7-881c830b57e3"),
                            BusId = new Guid("9c1d3c8c-99b6-4df7-bca1-74e78ce8e5ca"),
                            BusStopId = new Guid("e8a4cf7f-31fc-4b09-a57e-8a1c6e741b85"),
                            BusStopNo = 4
                        },
                        new
                        {
                            Id = new Guid("32a0e99a-8e4a-45c6-9f87-95cc71a35877"),
                            BusId = new Guid("9c1d3c8c-99b6-4df7-bca1-74e78ce8e5ca"),
                            BusStopId = new Guid("d6c9e7b3-268f-44a2-bf24-4e82eb6efb36"),
                            BusStopNo = 5
                        },
                        new
                        {
                            Id = new Guid("6d418f6c-2fe6-4c92-9c53-15e33a157a3b"),
                            BusId = new Guid("9c1d3c8c-99b6-4df7-bca1-74e78ce8e5ca"),
                            BusStopId = new Guid("c4e4a12d-2b5a-4a97-8493-327ad0869f6a"),
                            BusStopNo = 6
                        },
                        new
                        {
                            Id = new Guid("b654fad3-e38e-49d7-9ef5-d10a80a9a12e"),
                            BusId = new Guid("9c1d3c8c-99b6-4df7-bca1-74e78ce8e5ca"),
                            BusStopId = new Guid("7a3f1d02-5c79-4803-9a2f-1c8559d3077d"),
                            BusStopNo = 7
                        },
                        new
                        {
                            Id = new Guid("36e5411d-42a3-4d3f-9c0c-4bb4b6a2820c"),
                            BusId = new Guid("9c1d3c8c-99b6-4df7-bca1-74e78ce8e5ca"),
                            BusStopId = new Guid("6a65a3eb-901e-418f-bb3f-9ac0c68a9c64"),
                            BusStopNo = 8
                        },
                        new
                        {
                            Id = new Guid("d1286c35-42df-4777-9c9b-7402b9b3285c"),
                            BusId = new Guid("b5f8236a-927e-471e-8c75-66cf17f06df7"),
                            BusStopId = new Guid("cc376167-8b1a-4df7-bfd3-48e3542f73c5"),
                            BusStopNo = 1
                        },
                        new
                        {
                            Id = new Guid("c57193d8-4b0d-421f-82f1-06ff1ac50d75"),
                            BusId = new Guid("b5f8236a-927e-471e-8c75-66cf17f06df7"),
                            BusStopId = new Guid("5b5f8d4a-0c62-4c06-94e1-aa6f02a7a1df"),
                            BusStopNo = 2
                        },
                        new
                        {
                            Id = new Guid("7e9b530e-ae19-4b91-b53b-44f96b0e6011"),
                            BusId = new Guid("b5f8236a-927e-471e-8c75-66cf17f06df7"),
                            BusStopId = new Guid("9f7b8e26-3ac9-467d-9b3e-688a63b8d1e5"),
                            BusStopNo = 3
                        },
                        new
                        {
                            Id = new Guid("b63685df-2e68-4c25-8919-25b20f372e2a"),
                            BusId = new Guid("b5f8236a-927e-471e-8c75-66cf17f06df7"),
                            BusStopId = new Guid("e8a4cf7f-31fc-4b09-a57e-8a1c6e741b85"),
                            BusStopNo = 4
                        },
                        new
                        {
                            Id = new Guid("91e3ca2e-99a3-4b36-8801-7844d7cb82d9"),
                            BusId = new Guid("b5f8236a-927e-471e-8c75-66cf17f06df7"),
                            BusStopId = new Guid("d6c9e7b3-268f-44a2-bf24-4e82eb6efb36"),
                            BusStopNo = 5
                        },
                        new
                        {
                            Id = new Guid("3f7a2db2-e1d7-4923-bb42-1e5a1db41633"),
                            BusId = new Guid("b5f8236a-927e-471e-8c75-66cf17f06df7"),
                            BusStopId = new Guid("c4e4a12d-2b5a-4a97-8493-327ad0869f6a"),
                            BusStopNo = 6
                        },
                        new
                        {
                            Id = new Guid("8e5b193c-96c5-43a3-9e2e-19ce508cee53"),
                            BusId = new Guid("b5f8236a-927e-471e-8c75-66cf17f06df7"),
                            BusStopId = new Guid("7a3f1d02-5c79-4803-9a2f-1c8559d3077d"),
                            BusStopNo = 7
                        },
                        new
                        {
                            Id = new Guid("64a3c1f0-8931-4d9d-b739-aa5920f38388"),
                            BusId = new Guid("b5f8236a-927e-471e-8c75-66cf17f06df7"),
                            BusStopId = new Guid("6a65a3eb-901e-418f-bb3f-9ac0c68a9c64"),
                            BusStopNo = 8
                        },
                        new
                        {
                            Id = new Guid("f3e05278-9f5e-41d3-b37b-5d40c636d9f0"),
                            BusId = new Guid("b5f8236a-927e-471e-8c75-66cf17f06df7"),
                            BusStopId = new Guid("1e24207f-623a-4ab9-aa5a-16d21d986b82"),
                            BusStopNo = 9
                        });
                });

            modelBuilder.Entity("BusRouteManagementSystem.Model.BusStop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Busstop_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BusStop");

                    b.HasData(
                        new
                        {
                            Id = new Guid("42d08f38-8756-4c09-b5df-6a65b5f8d0fe"),
                            Busstop_Name = "Ratnapark"
                        },
                        new
                        {
                            Id = new Guid("6a65a3eb-901e-418f-bb3f-9ac0c68a9c64"),
                            Busstop_Name = "Koteshwor "
                        },
                        new
                        {
                            Id = new Guid("cc376167-8b1a-4df7-bfd3-48e3542f73c5"),
                            Busstop_Name = "Sankhu "
                        },
                        new
                        {
                            Id = new Guid("7fe7e1cb-63a2-4c6e-940f-63e7c85728c7"),
                            Busstop_Name = "Gangabu "
                        },
                        new
                        {
                            Id = new Guid("b8fbbac3-e95a-47c7-950f-75e73a2ea4c9"),
                            Busstop_Name = "Kalanki "
                        },
                        new
                        {
                            Id = new Guid("d2722cf0-2bfa-4e0e-b5c0-2c482c74b6a2"),
                            Busstop_Name = "Sundarijal "
                        },
                        new
                        {
                            Id = new Guid("1e24207f-623a-4ab9-aa5a-16d21d986b82"),
                            Busstop_Name = "Bhaktapur"
                        },
                        new
                        {
                            Id = new Guid("c4e4a12d-2b5a-4a97-8493-327ad0869f6a"),
                            Busstop_Name = "Chabhil"
                        },
                        new
                        {
                            Id = new Guid("5b5f8d4a-0c62-4c06-94e1-aa6f02a7a1df"),
                            Busstop_Name = "Thali"
                        },
                        new
                        {
                            Id = new Guid("9f7b8e26-3ac9-467d-9b3e-688a63b8d1e5"),
                            Busstop_Name = "Mulpani"
                        },
                        new
                        {
                            Id = new Guid("e8a4cf7f-31fc-4b09-a57e-8a1c6e741b85"),
                            Busstop_Name = "Jorpati"
                        },
                        new
                        {
                            Id = new Guid("d6c9e7b3-268f-44a2-bf24-4e82eb6efb36"),
                            Busstop_Name = "Bouddha"
                        },
                        new
                        {
                            Id = new Guid("7a3f1d02-5c79-4803-9a2f-1c8559d3077d"),
                            Busstop_Name = "Gausala"
                        },
                        new
                        {
                            Id = new Guid("2c171bb1-63a7-42d9-91e2-83de835c85a1"),
                            Busstop_Name = "Medical college"
                        },
                        new
                        {
                            Id = new Guid("e4b9c7d3-1f8a-4672-92e5-6c3dab7f5e9d"),
                            Busstop_Name = "Makalbari"
                        });
                });

            modelBuilder.Entity("BusBusStop", b =>
                {
                    b.HasOne("BusRouteManagementSystem.Model.Bus", null)
                        .WithMany()
                        .HasForeignKey("BusesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusRouteManagementSystem.Model.BusStop", null)
                        .WithMany()
                        .HasForeignKey("StopsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BusRouteManagementSystem.Model.BusBusStop", b =>
                {
                    b.HasOne("BusRouteManagementSystem.Model.Bus", "Bus")
                        .WithMany()
                        .HasForeignKey("BusId");

                    b.HasOne("BusRouteManagementSystem.Model.BusStop", "BusStop")
                        .WithMany()
                        .HasForeignKey("BusStopId");

                    b.Navigation("Bus");

                    b.Navigation("BusStop");
                });
#pragma warning restore 612, 618
        }
    }
}
